# Generated by Django 5.0.2 on 2024-02-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_remove_movie_director_movie_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(0, ''), (1, 'i'), (2, 'ii'), (3, 'iii'), (4, 'iiii'), (5, 'iiiii')], default=1),
        ),
    ]
