# Generated by Django 5.0.2 on 2024-03-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie', to='movie_app.director'),
        ),
    ]
